#!/bin/Rscript
qlibrary(viridis)
qlibrary(stringr)
qlibrary(fields)
source('utils.R')


# settings (filter range)
#rng <- list(min=-25, max=50)
rng <- list(min=-25, max=50)
#lkmeta <- read.table('lake_ids.txt', head=T)
lkmeta <- read.csv('csv/lks_SA.csv', head=T) # surface areas generated by plot_depth.R
lkmeta <- lkmeta[order(lkmeta$name),]



min_frac <- .3
ctlcol <- 'brown'
glocol <- 'orange'




calc_rmse <- function(mod, obs){ sqrt(mean((mod-obs)^2, na.rm=T)) }
calc_bias <- function(mod, obs){ mean(mod-obs, na.rm=T) }


obs <- read.table('txt/temp_out_mq3.txt')
frac <- read.table('txt/frac_out_mq3.txt')
obs[frac < min_frac] <- NA
lks <- names(obs)

dts_obs <- as.Date(row.names(obs), format='%Y%m%d', tz='z')


ctl <- read.table('csv/ctl_T3D.csv', row.names=1, sep=',')
glo <- read.table('csv/bi0m_T3D.csv', row.names=1, sep=',')

# confirm dims and t0 are identical
if (nrow(ctl) != nrow(glo)) stop('cases dont match')
if (row.names(glo)[1]!=row.names(ctl)[1]) stop('t0s dont match')

# filter for wild values
ctl <- filter_rng(ctl)
glo <- filter_rng(glo)
#glo2 <- filter_rng(glo2)
obs <- filter_rng(obs)

dts_mod <- as.POSIXct(row.names(ctl), 'z')
ymd <- format(dts_mod, '%Y%m%d')
ctl_rng <- aggregate(ctl, by=list(ymd), function(x) diff(range(x)))[,-1]
glo_rng <- aggregate(glo, by=list(ymd), function(x) diff(range(x)))[,-1]
ctl_dly <- aggregate(ctl, by=list(ymd), mean, na.rm=T)[,-1]
glo_dly <- aggregate(glo, by=list(ymd), mean, na.rm=T)[,-1]

ymd <- unique(ymd)
row.names(ctl_rng) <- ymd
row.names(glo_rng) <- ymd
row.names(ctl_dly) <- ymd
row.names(glo_dly) <- ymd

# INTERSECT DATES for OBS and MODEL 
comdts <- format(as.Date(intersect(as.Date(ymd,'%Y%m%d'), dts_obs)), '%Y%m%d')
comdts <- comdts[comdts<'20191220']  # ditch bad data post xmas (some ctl lakes blowup)

ctl_dly <- ctl_dly[comdts,]
glo_dly <- glo_dly[comdts,]
obs <- obs[comdts,]
dts <- as.Date(comdts, '%Y%m%d')


ctl <- ctl[dts_mod < as.POSIXct('2019-12-20','z'),]
glo <- glo[dts_mod < as.POSIXct('2019-12-20','z'),]
dts_mod <- dts_mod[dts_mod < as.POSIXct('2019-12-20','z')]

#dts_mod <- as.POSIXct(row.names(ctl), 'z')


#rmse <- matrix(nrow=length(lks), ncol=3, dimnames=list(lks, c('ctl','glo','glo2')))
rmse <- matrix(nrow=length(lks), ncol=2, dimnames=list(lks, c('ctl','glo')))
#bias <- rmse


seldts <- grep('2019-..-.. 18:00:00', dts_mod) # select the 12Z timestep to compare with obs
#seldts <- grep('2019-..-..$', dts_mod) 

# PART 1:  PLOT AND SKILL ASSESS FULL TIME SERIES
for (lk in lks){
	if(all(is.na(obs[,lk]))) next
	# run skill
	rmse[lk, 'ctl'] <- calc_rmse(ctl[seldts,lk], obs[,lk])
	rmse[lk, 'glo'] <- calc_rmse(glo[seldts,lk], obs[,lk])

#	rmse[lk, 'ctl'] <- calc_rmse(ctl_dly[,lk], obs[,lk])
#	rmse[lk, 'glo'] <- calc_rmse(glo_dly[,lk], obs[,lk])
}



# generate table
deps <- read.table('txt/depths_by_lake.txt')[,-3]
#dep_diff <- -apply(deps, 1, diff)/deps[,'ctl']
#dep_diff <- -apply(deps, 1, diff)/deps[,'ctl']

tbl <- lkmeta[c('name','area_km')]
#tbl$latitude <- round(meta$lat, digits=0)
tbl$name <- str_to_title(gsub('_',' ',tbl$name))
tbl$dep_flt <- deps[,'ctl']
tbl$dep_glo <- deps[,'glo']

# alphabetize glo, ctl, and rmse, bias(unused)
ctl_dly <- ctl_dly[,order(names(ctl_dly))]
glo_dly <- glo_dly[,order(names(glo_dly))]
frac <- frac[,order(names(frac))]
rmse <- rmse[order(row.names(rmse)),]
#bias <- bias[order(row.names(bias)),]


# intercomparison
tbl$rmsd <- apply(glo_dly-ctl_dly, 2, function(x) sqrt(mean(x^2, na.rm=T)))
rngdiff <- t(apply(glo_dly-ctl_dly, 2, function(x) range(x, na.rm=T)))
tbl$mindif <- rngdiff[,1]
tbl$maxdif <- rngdiff[,2]

# validation
tbl$frac <- apply(frac, 2, mean, na.rm=T)*100
tbl$rmse_diff <- apply(rmse[,c('ctl','glo')], 1, diff) # order of diff is UNINTUITIVE!

# remove lakes with no obs
#tbl <- tbl[is.finite(tbl$frac),]

# sort and calculate mean
#tbl <- tbl[order(tbl$rmse_diff, decreasing=T),]
tbl <- tbl[order(tbl$name),]
tbl$name <- gsub(' Lake', '', tbl$name)
tbl$name <- gsub('Mcconaugh', 'McConaugh', tbl$name)

tbl[nrow(tbl)+1,-1] <- apply(tbl[,-1], 2, mean, na.rm=T)
tbl[nrow(tbl),'name'] <- 'mean'
 

tbl$frac[is.na(tbl$frac)] <- 0
#tbl[tbl$name=='Great Salt Lake','dep_flt'] <- 0
#fmtstr='%15s, \t%4.0f,\t %1.0f,\t %1.0f,\t %3.0f,\t %4.2f,\t %3.1f,\t %3.1f\n'
#fmtstr='%15s,\t%4.0f,\t%1.0f,\t%1.0f,\t%3.0f,\t%4.2f,\t%3.1f,\t%3.1f\n'
fmtstr='%13s,\t%4.0f,\t%1.0f,\t%1.0f,\t%3.1f,\t%3.1f,\t%3.1f,\t%3.0f,\t%4.2f\n'
#fmtstr='%13s,\t%4.0f,\t%2.0f,\t%1.0f,\t%1.0f,\t%3.1f,\t%3.1f,\t%3.1f,\t%3.0f,\t%4.2f\n' # add lats
write(names(tbl), file='', sep=',\t', ncol=100)
cat(noquote(do.call('sprintf', c(fmtstr, tbl))))


